[package]
org = "ballerinai"
name = "transaction"
version = "@toml.version@"
distribution = "2201.14.0-20260527-050400-74f7e6bf"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
artifactId = "transaction"
version = "@project.version@"
path = "../transaction-native/build/libs/transaction-native-@project.version@.jar"
groupId = "ballerina"
