[package]
org = "ballerinai"
name = "transaction_negative_tests"
version = "1.11.0"

[platform.java25]
graalvmCompatible = true

[[platform.java25.dependency]]
path = "../transaction-native/build/libs/transaction-native-1.12.1-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "transaction"
version = "1.12.1-SNAPSHOT"

[[platform.java25.dependency]]
path = "../transaction-test-utils/build/libs/transaction-test-utils-1.12.1-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.transaction"
scope = "testOnly"
artifactId = "transaction"
version = "1.12.1-SNAPSHOT"

[[platform.java25.dependency]]
path = "./lib/io-native-1.8.0.jar"
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
version = "1.8.0"
